bowtie/_cli.py
=> Populate registry for dynamicRef.json

bowtie/_cli.py
reqd http://localhost:1234/draft2020-12/metaschema-no-validation.json
=> Populate registry for vocabulary.json

implementations/go-jsonschema/bowtie_jsonschema.go
- fix: Compiler.Draft is lost on next iteration
- use Compiler.LoadURL instead of jsonschema.LoadURL
- extract jsonschemaVersion, jsonReader, printJSON
=> Refactoring go-jsonschema impl

implementations/js-hyperjump/bowtie_hyperjump.js
Add skips for Hyperjump JSV.
I didn't figure out how to run it locally, so I hope it works.
=> Add skipped tests for Hyperjump JSV

implementations/js-hyperjump/bowtie_hyperjump.js
I noticed that some of my tests were still raising errors because the skip logic wasn't in the right place.
=> Fix hyperjump skipped tests implementation

implementations/js-hyperjump/bowtie_hyperjump.js
Addresses https://github.com/bowtie-json-schema/bowtie/issues/93 for Hyperjump JSV.
=> Hyperjump: Catch errors

implementations/dotnet-jsonschema-net/Program.cs, implementations/dotnet-jsonschema-net/bowtie_json_everything.csproj
bumping json-everything to the latest version
=> bump json-everything version to v4.0.0-beta2

implementations/rust-boon/Cargo.lock, implementations/rust-boon/Cargo.toml, implementations/rust-boon/src/main.rs
with this update, all tests should pass.
=> rust-boon: upgrade to v0.2

.github/workflows/report.yml, bowtie/_cli.py, bowtie/_report.py, bowtie/templates/report.html.j2
the UI/CSS may not be pretty. but it works
=> report: add links to other dialects

bowtie/_cli.py, tests/test_integration.py
Hey @Julian,
Changed the description key. Added language to the key. I sticked with dictionary only as it maintains the insertion order.
=> Display Validation using bowtie summary command

bowtie/_report.py
check current colours in README of https://github.com/santhosh-tekuri/boon
=> badge/fix: colors are too bright to read white font

bowtie/_cli.py, tests/test_integration.py
Hey @Julian,
Fixes #188 ,
Added the format flag to the info function and created a dictionary that stores the metadata of the implementations.
=> Displays JSON format for `bowtie info`

bowtie/templates/report.html.j2
https://user-images.githubusercontent.com/92979541/233057401-581b075c-6887-4273-9d9d-9492d264aea4.mp4
- Highlight the clicked instance row
- Did this because, If user scroll and forgot which one they clicked to see instance info. Now he / she can see that highlighted row
=> Highlight clicked Instance row for better User Experience

bowtie/_report.py
This PR adds the Supported Drafts Badge as mentioned in Issue #55.
=> Added Supported Draft Versions Badge

.github/workflows/report.yml, frontend/package-lock.json, frontend/package.json, frontend/src/App.js
Also changed regex for split function, it should handle Windows new lines as well
=> Change report files to .json

implementations/java-json-schema/BowtieJsonSchema.java, implementations/java-json-schema/build.gradle
Needed to adjust harness a little with new release, also:
- disable skipping vocabulary tests,
- fix response to dialect message
=> chore:  adjust dev.harrel:json-schema

frontend/src/components/CopyToClipboard.jsx
Tooltip for Copy button wasn't working in the previous code.
----
:books: Documentation preview :books:: https://bowtie-json-schema--421.org.readthedocs.build/en/421/
=> ✔️  Added the tooltip for copy Button

bowtie/schemas/io.json, implementations/java-json-schema/BowtieJsonSchema.java, tests/fauxmplementations/lintsonschema/schemas/io.json
----
:books: Documentation preview :books:: https://bowtie-json-schema--602.org.readthedocs.build/en/602/
=> update harness (dev.harrel) with support for draft 2019-09

bowtie/schemas/io.json, implementations/java-json-schema/BowtieJsonSchema.java, tests/fauxmplementations/lintsonschema/schemas/io.json
----
:books: Documentation preview :books:: https://bowtie-json-schema--603.org.readthedocs.build/en/603/
=> revert colon names

.github/dependabot.yml, implementations/java-mjs-validator/Dockerfile, implementations/java-mjs-validator/Harness.java, implementations/java-mjs-validator/build.gradle
Adding files to integrate mjs validator with bowtie
----
:books: Documentation preview :books:: https://bowtie-json-schema--416.org.readthedocs.build/en/416/
=> mjs Validator

implementations/kotlin-kmp-json-schema-validator/build.gradle.kts, implementations/kotlin-kmp-json-schema-validator/gradle/libs.versions.toml, implementations/kotlin-kmp-json-schema-validator/src/main/kotlin/BowtieSampsonSchemaValidatorLauncher.kt, implementations/kotlin-kmp-json-schema-validator/src/main/kotlin/Commands.kt, implementations/kotlin-kmp-json-schema-validator/src/main/kotlin/Responses.kt, implementations/kotlin-kmp-json-schema-validator/src/main/kotlin/TestFilters.kt
Add support for Draft 2019-09
----
📚 Documentation preview 📚: https://bowtie-json-schema--740.org.readthedocs.build/en/740/
=> Update kmp-json-schema-validator library version to 0.0.4

implementations/kotlin-kmp-json-schema-validator/gradle/libs.versions.toml, implementations/kotlin-kmp-json-schema-validator/src/main/kotlin/BowtieSampsonSchemaValidatorLauncher.kt, implementations/kotlin-kmp-json-schema-validator/src/main/kotlin/TestFilters.kt
Add support for draft 2020-12
----
📚 Documentation preview 📚: https://bowtie-json-schema--747.org.readthedocs.build/en/747/
=> Update Kotlin kmp json schema validator

implementations/java-json-schema-validator/BowtieJsonSchemaValidator.java
Fixes compilation errors due to changes in the newer versions.
----
📚 Documentation preview 📚: https://bowtie-json-schema--806.org.readthedocs.build/en/806/
=> Fix java-json-schema-validator compilation errors

implementations/dotnet-jsonschema-net/Program.cs
Fixes #632 
----
📚 Documentation preview 📚: https://bowtie-json-schema--845.org.readthedocs.build/en/845/
=> Include dotnet sdk version in Program.cs file

frontend/src/components/DragAndDrop/DragAndDrop.tsx
Fixes #331 
----
📚 Documentation preview 📚: https://bowtie-json-schema--849.org.readthedocs.build/en/849/
=> Fix rerouting back to Local Report after upload

frontend/src/components/Summary/ImplementationRow.css, frontend/src/components/Summary/ImplementationRow.tsx, frontend/src/components/Summary/SummaryTable.tsx
This pull request is a fix for https://github.com/bowtie-json-schema/bowtie/issues/873.
Fixed the size problem without any css modification.
----
📚 Documentation preview 📚: https://bowtie-json-schema--878.org.readthedocs.build/en/878/
=> Fix #873 issue. UI problem

frontend/src/DialectReportView.tsx, frontend/src/components/BowtieInfo/BowtieInfoSection.tsx
fix-#368 to show a description of what Bowtie is, on the homepage
----
📚 Documentation preview 📚: https://bowtie-json-schema--885.org.readthedocs.build/en/885/
=> Bowtie Info on Homepage

bowtie/_cli.py, tests/test_integration.py
Fixes #3 
@Julian plz have a look and let me know.
=> `--max-fail` and `--max-error` on `bowtie suite` and `bowtie run` commands

frontend/src/components/RunInfo/RunInfoSection.tsx
----
📚 Documentation preview 📚: https://bowtie-json-schema--936.org.readthedocs.build/en/936/
=> refactor: added left alignment for commit in run info

frontend/src/DialectReportView.tsx, frontend/src/ReportDataHandler.tsx, frontend/src/components/DragAndDrop/DragAndDrop.tsx
----
📚 Documentation preview 📚: https://bowtie-json-schema--938.org.readthedocs.build/en/938/
=> fix: showing about bowtie to only home page

frontend/src/components/Summary/ImplementationRow.css, frontend/src/components/Summary/ImplementationRow.tsx
resolves #944 
----
📚 Documentation preview 📚: https://bowtie-json-schema--946.org.readthedocs.build/en/946/
=> Fix hover details color

frontend/src/DialectReportView.tsx, frontend/src/components/NavBar.tsx
----
📚 Documentation preview 📚: https://bowtie-json-schema--965.org.readthedocs.build/en/965/
=> Fixed current Navbar and Container Related Issue.

implementations/kotlin-kmp-json-schema-validator/src/main/kotlin/TestFilters.kt
----
📚 Documentation preview 📚: https://bowtie-json-schema--978.org.readthedocs.build/en/978/
=> kmp-json-schema-validator: Remove format tests from excluded

action.yml
Looks like I didn't test the action well... Sorry for the problems it caused.
Related to #955 
----
📚 Documentation preview 📚: https://bowtie-json-schema--988.org.readthedocs.build/en/988/
=> Fix bowtie action: simplify the retry logic

implementations/clojure-json-schema/src/bowtie_json_schema/core.clj, implementations/ruby-json_schemer/bowtie_json_schemer.rb, implementations/ts-vscode-json-languageservice/bowtie_jsonls.ts
Rust, Ruby, C++ are still some of the few pending. Might be some more as well which I am missing. 
But for whoever reading this PR feel free to add more support on this one. Particularly getting this info in C++ is not straightforward is what I came across while Googling.
----
📚 Documentation preview 📚: https://bowtie-json-schema--1012.org.readthedocs.build/en/1012/
=> WIP:- Missing run infos in different languages

frontend/src/components/Summary/ImplementationRow.tsx
Fixes #1023 
https://github.com/bowtie-json-schema/bowtie/assets/68469605/908195a4-f1d9-4ada-a664-650ba6918b6e
=> Stop NavLink's onClick propagation

frontend/src/components/Summary/ImplementationRow.tsx
The class is called `text-primary-emphasis` in dark mode and `text-primary` in light mode. So it works correctly now :)
----
📚 Documentation preview 📚: https://bowtie-json-schema--1030.org.readthedocs.build/en/1030/
=> Fix dark mode implementation link

frontend/package.json, frontend/pnpm-lock.yaml, frontend/src/components/Cases/SchemaDisplay.tsx, frontend/src/components/CopyToClipboard.tsx
- Added Syntax highlighting using `react-syntax-highlihter` 
- Changed the copy btn icon
- Set timeout after 1.5 seconds to transition from `Copied` state to `Copy to clipboard` state again
----
📚 Documentation preview 📚: https://bowtie-json-schema--1062.org.readthedocs.build/en/1062/
=> Added syntax highlighting in the schema display and Changed the clipboard style to a minimal design

frontend/src/components/Cases/SchemaDisplay.tsx
----
📚 Documentation preview 📚: https://bowtie-json-schema--1064.org.readthedocs.build/en/1064/
=> JS -> JSON in syntax highlighting

frontend/src/components/Cases/SchemaDisplay.tsx, frontend/src/components/CopyToClipboard.tsx
=> Dynamic Theming for Schema Display color 

frontend/src/components/NavBar.tsx
Fixed hamburger menu not showing navbar items, resolving issue https://github.com/bowtie-json-schema/bowtie/issues/1068.
Replaced bootstrap collapse toggle logic with react-bootstrap collapse.
----
📚 Documentation preview 📚: https://bowtie-json-schema--1070.org.readthedocs.build/en/1070/
=> Fixed Hamburger Menu

.github/workflows/deploy-frontend.yml, .github/workflows/report.yml
Fixes #1133 
Hi @Julian I think this should fix the issue
----
📚 Documentation preview 📚: https://bowtie-json-schema--1154.org.readthedocs.build/en/1154/
=> Re-enabling deploying the new test reports every time the scheduled report workflow reruns

frontend/src/index.tsx
@Julian
----
📚 Documentation preview 📚: https://bowtie-json-schema--1171.org.readthedocs.build/en/1171/
=> Remove the image prefix from the frontend for now

.github/workflows/deploy-frontend.yml, frontend/src/index.tsx
@Julian I think this should finally work now as per our needs! :)
----
📚 Documentation preview 📚: https://bowtie-json-schema--1176.org.readthedocs.build/en/1176/
=> Removing `branch: main` dependence to get the latest frontend-build

implementations/dotnet-corvus-jsonschema/Program.cs
----
📚 Documentation preview 📚: https://bowtie-json-schema--1201.org.readthedocs.build/en/1201/
=> Added local metaschema

frontend/src/components/ImplementationReportView/EmbedBadges.tsx, frontend/src/components/ImplementationReportView/ImplementationReportView.tsx, frontend/src/components/OtherImplementations.tsx, frontend/src/components/Summary/ImplementationRow.tsx, frontend/src/data/parseReportData.test.ts, frontend/src/data/parseReportData.ts, frontend/src/index.tsx
Fixes #1204  
@Julian let me know if this is fine. Thanks!
https://github.com/bowtie-json-schema/bowtie/assets/68469605/0b4e92f4-4ae7-449a-bb8c-2945afbb10be
----
📚 Documentation preview 📚: https://bowtie-json-schema--1208.org.readthedocs.build/en/1208/
=> Fragment link for badge modal

implementations/dotnet-corvus-jsonschema/Program.cs
----
📚 Documentation preview 📚: https://bowtie-json-schema--1210.org.readthedocs.build/en/1210/
=> Platform details for Corvus

bowtie/_core.py
Closes #1187.
----
📚 Documentation preview 📚: https://bowtie-json-schema--1218.org.readthedocs.build/en/1218/
=> Dont poison containers until needed otherwise

bowtie/_cli.py, bowtie/schemas/cli/statistics.json, tests/fauxmplementations/lintsonschema/schemas/cli/statistics.json, tests/test_integration.py
=> `bowtie statistics` defaulting to retrieving latest dialect's latest report from published website

frontend/package.json
----
📚 Documentation preview 📚: https://bowtie-json-schema--1227.org.readthedocs.build/en/1227/
=> Update pnpm 9.1.2 -> 9.1.4

implementations/go-jsonschema/Dockerfile, implementations/go-jsonschema/bowtie_jsonschema.go, implementations/go-jsonschema/go.mod, implementations/go-jsonschema/go.sum
----
📚 Documentation preview 📚: https://bowtie-json-schema--1251.org.readthedocs.build/en/1251/
=> update go-jsonschema to v6.0.0

bowtie/_cli.py, docs/spelling-wordlist.txt, tests/test_integration.py
Fixes #1260 
----
📚 Documentation preview 📚: https://bowtie-json-schema--1261.org.readthedocs.build/en/1261/
=> `bowtie filter-implementations --direct`

bowtie/_cli.py, tests/fauxmplementations/miniatures.py, tests/test_integration.py
Closes #1270 
Sorry @Julian for closing the other one 😅. I had some issues on my workspaces environment.
----
📚 Documentation preview 📚: https://bowtie-json-schema--1284.org.readthedocs.build/en/1284/
=> Versioning info in `bowtie summary`

frontend/package.json, frontend/pnpm-lock.yaml
@Julian this works for now.
----
📚 Documentation preview 📚: https://bowtie-json-schema--1288.org.readthedocs.build/en/1288/
=> update pnpm and fix vulnerable braces package

.github/dependabot.yml, implementations/cpp-jsontoolkit/Dockerfile, implementations/cpp-jsontoolkit/bowtie_jsontoolkit.cpp
Still a very WIP, but would like to work on it in the open to make it easier to pair debug if needed (as I never added an implementation before!)
See: https://github.com/sourcemeta/jsontoolkit
----
📚 Documentation preview 📚: https://bowtie-json-schema--1293.org.readthedocs.build/en/1293/
=> Add JSON Toolkit to Bowtie

.github/dependabot.yml, implementations/rust-jsonschema/Cargo.lock, implementations/rust-jsonschema/Cargo.toml
Resolves #1203
----
📚 Documentation preview 📚: https://bowtie-json-schema--1304.org.readthedocs.build/en/1304/
=> Add groups to dependabot config

frontend/package.json
Will definitely figure out a way to automate this once I get some free time.
----
📚 Documentation preview 📚: https://bowtie-json-schema--1309.org.readthedocs.build/en/1309/
=> update pnpm (9.3.0 -> 9.4.0)

implementations/kotlin-kmp-json-schema-validator/gradle/libs.versions.toml, implementations/kotlin-kmp-json-schema-validator/src/main/kotlin/BowtieSampsonSchemaValidatorLauncher.kt, implementations/kotlin-kmp-json-schema-validator/src/main/kotlin/TestFilters.kt
----
📚 Documentation preview 📚: https://bowtie-json-schema--1314.org.readthedocs.build/en/1314/
=> Update version: support for draft6 and draft4

.github/workflows/versioned-report.yml
Hi @Julian sorry for this minor mistake 😅. Can we try rerunning once again ?
----
📚 Documentation preview 📚: https://bowtie-json-schema--1374.org.readthedocs.build/en/1374/
=> Minor directory name fix in `versioned-report.yml` workflow

implementations/java-json-schema/BowtieJsonSchema.java
Hopefully, for any new spec draft support it will happen automatically from now on
----
📚 Documentation preview 📚: https://bowtie-json-schema--1397.org.readthedocs.build/en/1397/
=> Chore: dev.harrel implementation - add support for draft7

bowtie/schemas/models/dialect.json, bowtie/tests/fauxmplementations/lintsonschema/schemas/models/dialect.json
----
📚 Documentation preview 📚: https://bowtie-json-schema--1409.org.readthedocs.build/en/1409/
=> add id to dialect uri in json schema

.github/workflows/report.yml, bowtie/schemas/api/v1/json-schema-org/implementations.json, bowtie/tests/fauxmplementations/lintsonschema/schemas/api/v1/json-schema-org/implementations.json
@Julian I think you can re-trigger the workflow after this
----
📚 Documentation preview 📚: https://bowtie-json-schema--1415.org.readthedocs.build/en/1415/
=> minor key names renaming and refactoring in json-schema.org implementations file

implementations/cpp-jsontoolkit/bowtie_jsontoolkit.cpp
----
📚 Documentation preview 📚: https://bowtie-json-schema--1427.org.readthedocs.build/en/1427/
=> Run JSON Toolkit on 2019-09

.github/workflows/ci.yml, .github/workflows/images.yml
Fixes #1410 
----
📚 Documentation preview 📚: https://bowtie-json-schema--1429.org.readthedocs.build/en/1429/
=> Generating attestations for wheels and images

docs/requirements.txt, pyproject.toml, requirements.txt, test-requirements.txt
Particularly for the security vulnerability.
----
📚 Documentation preview 📚: https://bowtie-json-schema--1442.org.readthedocs.build/en/1442/
=> Try unpinning aiohttp.

implementations/cpp-jsontoolkit/bowtie_jsontoolkit.cpp
----
📚 Documentation preview 📚: https://bowtie-json-schema--1443.org.readthedocs.build/en/1443/
=> Run JSON Toolkit against 2020-12

implementations/rust-jsonschema/Cargo.lock, implementations/rust-jsonschema/Cargo.toml, implementations/rust-jsonschema/src/main.rs
----
📚 Documentation preview 📚: https://bowtie-json-schema--1566.org.readthedocs.build/en/1566/
=> Update rust-jsonschema to 0.22.1

implementations/rust-jsonschema/Cargo.lock, implementations/rust-jsonschema/Cargo.toml
Almost done with supporting all drafts :)
----
📚 Documentation preview 📚: https://bowtie-json-schema--1587.org.readthedocs.build/en/1587/
=> Update rust-jsonschema to 0.23

.github/dependabot.yml, .github/workflows/images.yml, implementations/cpp-jsoncons/.gitignore, implementations/cpp-jsoncons/CMakeLists.txt, implementations/cpp-jsoncons/Dockerfile, implementations/cpp-jsoncons/bowtie_jsoncons.cpp, implementations/cpp-jsoncons/vcpkg-configuration.json, implementations/cpp-jsoncons/vcpkg.json
----
📚 Documentation preview 📚: https://bowtie-json-schema--1634.org.readthedocs.build/en/1634/
=> Add jsoncons implementation

implementations/elixir-jsv/.gitignore, implementations/elixir-jsv/Dockerfile, implementations/elixir-jsv/lib/bowtie_jsv.ex, implementations/elixir-jsv/mix.exs
Yet another try.
Beyond this I'm not sure what to try next. I'll have to build an environment that can reproduce the CI more precisely.
----
📚 Documentation preview 📚: https://bowtie-json-schema--1806.org.readthedocs.build/en/1806/
=> chore: Convert elixir-jsv harness to escript

implementations/cpp-jsoncons/bowtie_jsoncons.cpp
Added a URI resolver in bowtie_jsoncons.cpp
----
📚 Documentation preview 📚: https://bowtie-json-schema--1815.org.readthedocs.build/en/1815/
=> [cpp-jsoncons] Added a URI resolver in bowtie_jsoncons.cpp

implementations/rust-boon/src/main.rs
----
📚 Documentation preview 📚: https://bowtie-json-schema--1839.org.readthedocs.build/en/1839/
=> fix: fix boon broken issues link

bowtie/benchmarks/useless_keywords.py
----
📚 Documentation preview 📚: https://bowtie-json-schema--1857.org.readthedocs.build/en/1857/
=> fix: fix empty useless keywords generator

implementations/cpp-blaze/CMakeLists.txt, implementations/cpp-blaze/Dockerfile, implementations/cpp-blaze/bowtie_blaze.cpp
----
📚 Documentation preview 📚: https://bowtie-json-schema--1870.org.readthedocs.build/en/1870/
=> Upgrade Blaze commit to `0424f5765c4c18162a7f7ed8354134e680f6664e`

bowtie/_cli.py, bowtie/_direct_connectable.py, bowtie/tests/miniatures.py, bowtie/tests/test_integration.py
Closes #1518.
----
📚 Documentation preview 📚: https://bowtie-json-schema--1858.org.readthedocs.build/en/1858/
=> feat: improve bowtie info pretty output

frontend/package.json, frontend/pnpm-lock.yaml
This PR updates frontend deps to the latest available version. It also resolves failing UI tests - the driver location was changed after the new playwright release
----
📚 Documentation preview 📚: https://bowtie-json-schema--1879.org.readthedocs.build/en/1879/
=> Update frontend dependencies

bowtie/_cli.py
----
📚 Documentation preview 📚: https://bowtie-json-schema--1883.org.readthedocs.build/en/1883/
=> refactor: add global stdout rich console

frontend/src/components/BenchmarkResults/BenchmarkSummarySection.tsx, frontend/src/data/parseReportData.test.ts, implementations/lua-jsonschema/Dockerfile
This pull request includes several small changes across different files to improve comments and correct minor issues.
Improvements and corrections:
* [`frontend/src/components/BenchmarkResults/BenchmarkSummarySection.tsx`](diffhunk://#diff-4eba142adf3ea40d5a32fd2a2742255ed1b1ad7942acd9f81c2b99c8d3498ccdL107-R107): Corrected a typo in a comment to ensure clarity.
* [`frontend/src/data/parseReportData.test.ts`](diffhunk://#diff-a835af739ef6bbee6f3a47b7fdb27242edcdb3e38883231a6fcd85e6ecd3fcacL50-R50): Added a comma in a comment for better readability.
* [`implementations/lua-jsonschema/Dockerfile`](diffhunk://#diff-c304c83eb7d66adbb22a949c62c9f7eaeff7364496c5a0ed56e3b679301b9498L11-R11): Added a missing slash to the `COPY` command for consistency.
----
📚 Documentation preview 📚: …
=> Small fixes
