implementations/dotnet-jsonschema-net/bowtie_json_everything.csproj

Should fix the `unevaluated*` issues.

bump JsonSchema.Net to v3.3.2

---

implementations/dotnet-jsonschema-net/Program.cs

This should handle (kind of) the `multipleOf` test, which just isn't supported.

Skip bignum multipleof test for JsonSchema.Net

---

.github/workflows/images.yml

Lets 'em fail separately, preps for matrix'ing by platform, and seems to speed up builds by ~2x with the parallelism.
Also run `smoke` before we push, we don't want to push the new version if it fails.

Try building images via a build matrix.

---

implementations/js-hyperjump/bowtie_hyperjump.js

I noticed that I was skipping tests in 2019-09/2020-12 that should only be skipped in draft-07 and under. So, I refactored to take the dialect into account when skipping tests.

Hyperjump: Allow a different set of skips per dialect

---

implementations/js-hyperjump/bowtie_hyperjump.js

This might fix the problem with the version not showing for `hyperjump-jsv` on the homepage.

Attempt to fix Hyperjump JSV version not showing

---

implementations/rust-boon/Cargo.lock

this version gets rid of `chrono` dependency, to fix security vulnerability

rust-boon: update to v0.2.1

---

bowtie/templates/report.html.j2

This PR resolves issue [#53](https://github.com/bowtie-json-schema/bowtie/issues/53) and makes the following changes:
1. Shows the combined errors + failures numbers as unsuccessful in the report.
2. Gives the description of errors and failures when hovering over the unsuccessful heading.
3. Shows the errors + failures numbers when hovering over any unsuccessful number in the report.

Showing the combined errors + failures number in reports 

---

bowtie/schemas/io-schema.json
implementations/go-gojsonschema/bowtie_gojsonschema.go
implementations/go-jsonschema/bowtie_jsonschema.go
implementations/js-ajv/bowtie_ajv.js
implementations/js-hyperjump/bowtie_hyperjump.js
implementations/python-fastjsonschema/bowtie_fastjsonschema.py
implementations/python-jschon/bowtie_jschon.py
implementations/python-jsonschema/bowtie_jsonschema.py

This PR adds runtime information (including `os`, `os_version`, and `language_version`) to the implementation harness' metadata which is returned by `bowtie info` !
This is a subset PR that adds runtime info to JavaScript and Python based harnesses, and other harnesses' info will be added down the line in this PR itself.
Edit:
Golang based harnesses are also modified to add runtime info.

Add runtime info to harness' metadata

---

.github/workflows/images.yml
implementations/rust-boon/Dockerfile
implementations/rust-jsonschema/Dockerfile

https://github.com/actions/runner-images/discussions/7188
the above issue says it ubuntu-20.04 is not affected by this

Build rust images using cargo's sparse registry option, reducing their memory usage

---

docs/implementers.rst

The image building is getting an error when done in docker.
``` bash
docker build --quiet -f Dockerfile -t bowtie-lua-jsonschema
```
Updated the documentation so that it works now in both podman, docker.

Update tutorial of bowtie documentation

---

.github/workflows/build-frontend.yml
frontend/src/index.jsx

Things got a little complicated with custom domain name. It now requires base url to be equal to `/`, but for fork deployments it still should be `/bowtie` (e.g. link `https://harrel56.github.io/assets/index-e150a41d.js` should be `https://harrel56.github.io/bowtie/assets/index-e150a41d.js`). This PR introduces a way to control base url using GH variable (`BOWTIE_BASE_URL`). I did it so if the variable is absent it uses `/bowtie` value. This way all future fork deployments should work without any additional configuration, but the original bowtie repo should set up a variable (`BOWTIE_BASE_URL` with value `/`) in order to work correctly.
@Julian Let me know what you think about this approach, couldn't come up with anything simpler and ofc I'm open to other ideas.
----
:books: Documentation …

fix: Support for multiple BASE_URL variables

---

frontend/src/components/NavBar.jsx

----
:books: Documentation preview :books:: https://bowtie-json-schema--404.org.readthedocs.build/en/404/

feat: add a button in the UI to access documentation page

---

implementations/js-hyperjump/bowtie_hyperjump.js

I noticed that a [fix](https://github.com/bowtie-json-schema/bowtie/pull/325) I made previously to my test harness didn't actually work the way I thought it did and wasn't working for draft-04. This appears to fix the problem.
(I managed to get it to run this time and verify that it works. I needed to use docker instead of podman to build the images. When I built the image with podman like the documentation says, bowtie couldn't find the image. When I built with docker instead, everything worked as expected.)
----
:books: Documentation preview :books:: https://bowtie-json-schema--413.org.readthedocs.build/en/413/

Fix Hyperjump test harness for file URIs

---

.github/workflows/build-frontend.yml

This probably stopped working when switch to pnpm occurred - provided change works on my fork, hopefully will work fine on main repo as well :)
----
:books: Documentation preview :books:: https://bowtie-json-schema--465.org.readthedocs.build/en/465/

try fixing fork GH deployment

---

implementations/java-json-schema-validator/BowtieJsonSchemaValidator.java
implementations/java-json-schema/BowtieJsonSchema.java

Seems that `java.vendor.version` is optional property and it's not provided in liberica. No idea how all images managed to build on my fork - must have mixed something up I guess
----
:books: Documentation preview :books:: https://bowtie-json-schema--469.org.readthedocs.build/en/469/

Fix failing smoke tests for java images

---

frontend/src/components/ImplementationReportView/DialectCompliance.tsx
frontend/src/data/Dialect.ts

The PR resolves issue #677 
Added firstPublicationDate in Dialects
Sorted compliance table in implementation page by compliance(fewer failed tests at the top) and break ties by publication date
----
📚 Documentation preview 📚: https://bowtie-json-schema--723.org.readthedocs.build/en/723/

Add firstPublicationDate in Dialects and sorts compliance table in implementation page.

---

implementations/js-hyperjump/bowtie_hyperjump.js

I just released a v1.7.0 and needed to make an update to the skipped tests. I made a few other improvements while I was at it.
Change log:
* I no longer allow schemas to self-identify using a `file:` URI scheme for security reasons. I arranged to skip those tests and simplified the retrievalURI construction that no longer needs to take into account `file:` URIs.
* Remove some tests from skipped that got moved to "optional"
* Fixed an issue where I was skipping tests I didn't need to. Oops.
* Renamed the implementation. Since v1.0.0, I haven't been using "JSV" because I consolidated all the components into one package. It's no longer just a validator, it's also a bundler, annotator, etc. Ideally I'd use the npm handle `@hyperjump/json-schema`, but for some reason the allowed characters are …

Update @hyperjump/json-schema for v1.7.0

---

implementations/scala-mjs-validator/Harness.scala

Two tests containing Unicode code points were renamed in the draft 2020-12 Test Suite. MJS does currently not support Unicode. This adds the new names to the set of unsupported tests.
For backwards-compatibility with older version of the draft 2020-12 Test Suite, we keep the previous names of the tests.
----
📚 Documentation preview 📚: https://bowtie-json-schema--769.org.readthedocs.build/en/769/

Update unsupported tests of MJS

---

implementations/kotlin-kmp-json-schema-validator/src/main/kotlin/BowtieSampsonSchemaValidatorLauncher.kt
implementations/kotlin-kmp-json-schema-validator/src/main/kotlin/TestFilters.kt

Added support for referencing remote schemes
----
📚 Documentation preview 📚: https://bowtie-json-schema--808.org.readthedocs.build/en/808/

Update kotlin-kmp-json-schema-validator: validator now supports remote schemes

---

implementations/java-json-schema-validator/BowtieJsonSchemaValidator.java

This fixes the issues it has running tests, for instance not being able to load https://json-schema.org/draft/2020-12/schema.
----
📚 Documentation preview 📚: https://bowtie-json-schema--811.org.readthedocs.build/en/811/

Fix java-json-schema-validator issues

---

frontend/src/components/Cases/CaseItem.tsx

**This pull request addresses #543.**
The goal is to highlight the test case which has been selected as currently it's impossible to tell which case is shown in the "instance" column.
**Implemented Enhancement:** 
Highlighted the selected test case in a greyish gradient so that it is distinguishable from the other test cases.
----
📚 Documentation preview 📚: https://bowtie-json-schema--827.org.readthedocs.build/en/827/

Highlight the selected test case

---

.gitpod.yml
docs/gitpod-motd.txt

This pull request addresses #695.
The goal is to populate the Gitpod MOTD with Bowtie documentation showing some example commands as well for using Bowtie.
Implementation:
1. Created a txt file containing the message to be shown in the MOTD in docs folder.
2.  Added task in gitpod yml to copy this message to the workspace motd file.
Preview of ssh:
Preview of web-ui:
----
📚 Documentation preview 📚: https://bowtie-json-schema--830.org.readthedocs.build/en/830/

Populate the GitPod MOTD with Bowtie documentation

---

implementations/scala-mjs-validator/Harness.scala

Some tests were skipped as a leftover artifact due to restrictions in an older version that are already resolved in the current MJS version (v0.1.0).
----
📚 Documentation preview 📚: https://bowtie-json-schema--832.org.readthedocs.build/en/832/

Update skipped tests for MJS validator

---

bowtie/_cli.py
pyproject.toml
tests/test_integration.py

**This pull request addresses #831.**
The goal is to add markdown formatter to commands for interoperability with other human-reader-targeted tooling.
Added --format option: markdown to be able to give output in markdown format for commands such as bowtie summary, bowtie info, bowtie smoke, etc.
**1. bowtie summary with show failures**
**2. bowtie summary with results**
**3. bowtie info**
**4. bowtie smoke** 
----
📚 Documentation preview 📚: https://bowtie-json-schema--839.org.readthedocs.build/en/839/

add --format markdown to commands

---

frontend/src/components/Cases/CaseItem.tsx

This pull request addresses #846.
The goal is that on the fronted, the screen must auto scroll to the top of the grid on clicking any test case such that schema and instance can be seen.
----
📚 Documentation preview 📚: https://bowtie-json-schema--847.org.readthedocs.build/en/847/

Auto scroll to the instance when some test is clicked

---

.github/workflows/images.yml
.github/workflows/report.yml

This pull request addresses #850.
The goal is to emit the bowtie smoke output in images.yml workflow and bowtie summary output in report.yml workflow to the github actions summary.
----
📚 Documentation preview 📚: https://bowtie-json-schema--843.org.readthedocs.build/en/843/

Show bowtie summary & bowtie smoke output in GITHUB_STEP_SUMMARY

---

.github/workflows/report.yml

This pull request addresses #448.
Incorporated the changes in workflow to store the previous reports in a separate folder
----
📚 Documentation preview 📚: https://bowtie-json-schema--851.org.readthedocs.build/en/851/

Save older build reports separately to track changes

---

frontend/src/components/Summary/ImplementationRow.tsx

**This pull request solves #867.**
**Implementation:**
Dont show the details button if the implementations has no errored, no skipped and no failed tests.
Screenshot:
----
📚 Documentation preview 📚: https://bowtie-json-schema--869.org.readthedocs.build/en/869/

Hide the details button on reports when there are no failures

---

frontend/src/components/ImplementationReportView/ImplementationReportView.tsx

fix #333: Added code to Implementation Info page to display Additional Links (URLs) provided by JSON schema implementers.
----
📚 Documentation preview 📚: https://bowtie-json-schema--879.org.readthedocs.build/en/879/

fix-#333: add extra info on UI

---

frontend/src/components/ImplementationReportView/ImplementationReportView.tsx

@harrel56, shortened version of code introduced a minor UI error, hence reverted to verbose code from previous version. See screenshots below.
Summarising from #879 here:
The shortened code, implementation.links?.length, leads to a UI bug (see the 0 displayed) when no additional Links are present:
The long form of code, implementation.links && !!implementation.links.length, meets the expected behavior:
The shortened version seems to be printing the value of length when there is no link to display. I'll revert to the long form of code.
----
📚 Documentation preview 📚: https://bowtie-json-schema--882.org.readthedocs.build/en/882/

code optimisation introduced an UI error #879

---

frontend/src/components/Cases/SchemaDisplay.tsx

Resolves https://github.com/bowtie-json-schema/bowtie/issues/544.
Here's how it looks:
I wasn't able to find a way to do this with just bootstrap so I added CSS to it. I'm not sure if it's better to keep it inline or extract it into a separate file (since the codebase seems to contain a mix of both) but it made sense to me to keep it inline for just one line of CSS. Happy to adjust the height if desired.
----
📚 Documentation preview 📚: https://bowtie-json-schema--923.org.readthedocs.build/en/923/

Add max height to schema and instance displays

---

frontend/src/components/Cases/SchemaDisplay.tsx

Fixes: #943
Instance copy button is now not overflowing in Mobile mode
----
📚 Documentation preview 📚: https://bowtie-json-schema--950.org.readthedocs.build/en/950/

Instance copy button is now not overflowing in Mobile mode

---

docs/contributing.rst

@Julian, I think there is some room for improvement, but I need your feedback on how to improve it 
----
📚 Documentation preview 📚: https://bowtie-json-schema--967.org.readthedocs.build/en/967/

[Docs] Added Instructions for building the documentations 

---

.github/workflows/ci.yml
.github/workflows/report.yml
action.yml

This PR adds the following parameters to bowtie action
- exact version to be installed. If not specified the latest available will be installed
- timeout in seconds to wait until the specified version becomes available
Resolves #955 
----
📚 Documentation preview 📚: https://bowtie-json-schema--981.org.readthedocs.build/en/981/

Install the exact version of bowtie when creating report

---

bowtie/_cli.py
pyproject.toml
requirements.txt

Closes #863.
The goal was to support syntax highlighting for schemas and instances in bowtie's cli.
**Implementation**
Created a custom lexer that understands JSON schema dialect. The lexer has already been published and can be installed using `pip install jsonschema_lexer`. Using this lexer, its pretty easy to add syntax highlighting support using rich's syntax module.
**Comparison of output**
**- Output now looks like:**
**- Output before:**
----
📚 Documentation preview 📚: https://bowtie-json-schema--975.org.readthedocs.build/en/975/

Add Support for Syntax Highlighting using jsonschema_lexer

---

frontend/src/components/Cases/CaseItem.tsx

While not my original intention, resolves #990
Before:
After:
----
📚 Documentation preview 📚: https://bowtie-json-schema--991.org.readthedocs.build/en/991/

Show first test instance by default

---

frontend/src/DialectReportView.tsx
frontend/src/components/Cases/CaseItem.tsx
frontend/src/components/Cases/CasesSection.tsx
frontend/src/components/Modals/DetailsButtonModal.tsx
frontend/src/components/Summary/ImplementationRow.tsx
frontend/src/components/Summary/SummaryTable.tsx
frontend/src/data/parseReportData.test.ts
frontend/src/data/parseReportData.ts

Fixes #997 
> implementation metadata duplicated twice, including once mixed in with counts which are used for counting the number of tests with various outcomes. We should remove this duplication
@Julian I have removed the metadata duplication from the **counts** as you mentioned above (you can check in the `parseReportData.test.ts` code). Adding some more UI tests is still in progress. But would like to hear out your opinion on these changes because this small tweak has called out for lot of refactoring.  
----
📚 Documentation preview 📚: https://bowtie-json-schema--999.org.readthedocs.build/en/999/

Removing metadata duplication and some more UI Tests

---

bowtie/_cli.py
bowtie/_core.py
tests/test_integration.py

Closes #996.
The goal is to add a `filter-dialects` subcommand supporting filtering of dialects like `filter-implementations`.
Command features:
1. Dialects are always sorted from newest to oldest.
<p>
2. `bowtie filter-dialects --latest` returns only the latest dialect.
<p>
3. `bowtie filter-dialects -i go-jsonschema` returns only the dialects supported by the implementation `go-jsonschema`.
<p>
4. `bowtie filter-dialects --boolean-schemas` returns only the dialects which support boolean schemas.
<p>
5. `bowtie filter-dialects --no-boolean-schemas` returns only the dialects which do not support boolean schemas.
----
📚 Documentation preview 📚: https://bowtie-json-schema--1002.org.readthedocs.build/en/1002/

Add filter-dialects subcommand

---

frontend/src/components/ImplementationReportView/DialectCompliance.tsx
frontend/src/components/NavBar.tsx
frontend/src/components/OtherImplementations.tsx
frontend/src/data/Dialect.test.ts
frontend/src/data/Dialect.ts

Fixes #962 by moving logic for creating dialect route paths into Dialect class itself, providing a single point of failure rather than multiple opportunities for errors in writing route paths for dialects. The paths are still technically hardcoded, but as mentioned by @harrel56 in #962, this is common practice.
In the process of this fix I did experiment quite a lot with TypeScript and what we can do as far as validating paths goes. I think there is a bigger project here that could be worked on over a larger time frame which allows for validation of paths and path parameters via TypeScript to prevent errors in specifying routes - along the lines of what is discussed [here](https://dev.to/0916dhkim/type-safe-usage-of-react-router-5c44). Since this is a bigger project that would introduce …

Remove hardcoded paths / links to dialect reports

---

test-requirements.in
test-requirements.txt
tests/test_integration.py

Closes #922.
Uses markdown-it-py with gfm and tries parsing the markdown to html. If the resultant token classes match our intended token classes, we get valid markdown.
----
📚 Documentation preview 📚: https://bowtie-json-schema--1022.org.readthedocs.build/en/1022/

Add tests to check that we emit valid markdown

---

bowtie/_cli.py
test-requirements.in
test-requirements.txt
tests/test_integration.py

https://github.com/bowtie-json-schema/bowtie/assets/68469605/03d0412f-a1a1-45d5-8990-c804c4e2e352
@Julian I am not sure why the test I wrote is failing though :(. Its some `process.returncode` of 78. Does it have something to do with the `ls implementations/` that's happening in the background ?. The command does work on the CLI without starting any Docker containers.
Also shouldn't we output directly without starting the containers even if it was just `bowtie filter-implementations -i python-jsonschema` with no arguments for e.g. ?
----
📚 Documentation preview 📚: https://bowtie-json-schema--1020.org.readthedocs.build/en/1020/

Speed up `bowtie filter-implementations` with no arguments

---

bowtie/_cli.py
test-requirements.txt

For some reason when I ran `pip-compile --strip-extras test-requirements.in` for adding `pexpect` it added `colorama` as a test dependency [here](https://github.com/bowtie-json-schema/bowtie/pull/1020/files#diff-fac4c6890301d4de5c3f4266837803d5240c84a3d8b6c735bbc6a64c39d2f94e) (via `click` and `pytest`) which wasn't already present in our `test-requirements.txt`, so no need!. 
Also removed the `.split` logic and used `.removeprefix` just like how we do in the other case.
----
📚 Documentation preview 📚: https://bowtie-json-schema--1049.org.readthedocs.build/en/1049/

Remove colorama from test requirements

---

frontend/src/components/Cases/CaseItem.tsx
frontend/src/components/Cases/CasesSection.tsx
frontend/src/components/Modals/DetailsButtonModal.tsx
frontend/src/components/Summary/ImplementationRow.tsx
frontend/src/components/Summary/SummaryTable.tsx
frontend/src/data/parseReportData.test.ts
frontend/src/data/parseReportData.ts

This PR does the following changes
**BEFORE**
```typescript 
export interface ImplementationResults {
id: string;
cases: Map<number, CaseResult[]>;
erroredCases: number;
skippedTests: number;
failedTests: number;
erroredTests: number;
}
```
**AFTER**
```typescript
export interface ImplementationResults {
caseResults: Map<number, CaseResult[]>;
totals: Partial<Totals>;
}
```
@Julian instead of doing the above I can also do
```typescript
export interface ImplementationResults extends Partial<Totals>{
caseResults: Map<number, CaseResult[]>;
}
```
both of them would work the same way only difference being the second way wouldn’t require a `totals` key explicitly.

Removing redundant `id` field from `ImplementationResults` interface and some deduplication and renaming (independent of PR #1058)

---

bowtie/_cli.py
docs/cli.rst
docs/conf.py
docs/requirements.in
docs/requirements.txt
docs/spelling-wordlist.txt

Fixes #802 
Hi @Julian 
The shell completion for implementations is working fine 👍 along with the completions for other bowtie commands and command options as well. Here's a demo :)
https://github.com/bowtie-json-schema/bowtie/assets/68469605/fb4d3fb7-e92e-41b9-aa37-3cfb5d14d181
I have some queries though:
1) We could add shell completions for languages as well ? and/or any other completions you've in mind ?
2) Regarding the automatically enabled shell completion for Homebrew installation that you asked for, pardon me but I am very much new to Homebrew formulae and Ruby 😅 (my local machine is Windows :( )  so I tried thinking of putting the below Ruby script in the [Homebrew install formula](https://github.com/bowtie-json-schema/homebrew-tap/blob/d106aa46ce80f643db9ccbd3f3cf9352205cc07b/bo …

Tab completion for Bowtie commands and implementations

---

bowtie/_cli.py
bowtie/schemas/cli/info.json
bowtie/schemas/cli/smoke.json
bowtie/schemas/cli/summary.json
bowtie/schemas/models/group.json
bowtie/schemas/models/implementation-id.json
bowtie/schemas/models/registry.json
bowtie/schemas/models/test.json
docs/requirements.txt
pyproject.toml
requirements.txt
test-requirements.txt
tests/fauxmplementations/lintsonschema/schemas/cli/info.json
tests/fauxmplementations/lintsonschema/schemas/cli/smoke.json
tests/fauxmplementations/lintsonschema/schemas/cli/summary.json
tests/fauxmplementations/lintsonschema/schemas/models/group.json
tests/fauxmplementations/lintsonschema/schemas/models/implementation-id.json
tests/fauxmplementations/lintsonschema/schemas/models/registry.json
tests/fauxmplementations/lintsonschema/schemas/models/test.json
tests/test_integration.py
tests/test_schemas.py

They're each available at `bowtie foo --schema` so that folks can know what output to expect.
Some improvement both to the schemas as well as output itself is certainly still possible.
We should at some point also render these in the docs.
----
📚 Documentation preview 📚: https://bowtie-json-schema--1124.org.readthedocs.build/en/1124/

Add JSON Schemas for all JSON CLI output other than our report

---

.github/workflows/deploy-frontend.yml

Default `report_artifact_in_scope` to false to be sure build frontend runs if workflow triggered by release published and not requiring successful dependent jobs 
Reference Docs:- https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-not-requiring-successful-dependent-jobs
----
📚 Documentation preview 📚: https://bowtie-json-schema--1163.org.readthedocs.build/en/1163/

Default `report_artifact_in_scope` to false to be sure build frontend runs if workflow triggered by release published

---

.github/workflows/deploy-frontend.yml

[Last workflow run](https://github.com/bowtie-json-schema/bowtie/actions/runs/9006736249/job/24745041155)
@Julian Unless we don't do this here as well then even if the `collect` job was successful having `build-frontend` as skipped still the skipped chain propagates down to `deploy` job because of its indirect dependency on `build-frontend` through `collect` ([reference](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idneeds)). Doing this check here as well ensures that this job definitely runs only if not failure in any of it's parent jobs.
Tested this and works on my workflow fork 👍. Below SS for reference.
`if: inputs.report_artifact_in_scope == true`
`if: inputs.report_artifact_in_scope == false`
Ignore my `deploy` job failure as I …

Propagate !failure() checks till last job

---

implementations/dotnet-jsonschema-net/Program.cs

Fixed an issue with registry lookups.
.Net `Uri` comparisons don't consider the fragment, and v7 now passes the complete URI into the `Fetch` function.  When Bowtie `.ToString()`s the URI to perform a string lookup, it includes the fragment and (rightly) can't find it.
This change updates the registry lookup so that it's a `Uri` key and the fragment will be ignored.
----
📚 Documentation preview 📚: https://bowtie-json-schema--1186.org.readthedocs.build/en/1186/

Update dotnet-jsoneverything-net registry lookup for lib v7

---

.gitignore
implementations/dotnet-corvus-jsonschema/Program.cs
implementations/dotnet-corvus-jsonschema/bowtie_corvus_jsonschema.csproj

1. Support generating code with "do not assert format" for 2020-12
2. Add missing `unevaluated` metaschema for 2020-12
3. Added .vs folder to the .gitignore section for "editor cruft"
----
📚 Documentation preview 📚: https://bowtie-json-schema--1205.org.readthedocs.build/en/1205/

Fixed bowtie test errors

---

frontend/package.json
frontend/pnpm-lock.yaml

@Julian your commit in here https://github.com/bowtie-json-schema/bowtie/commit/2a9152cf964e4663a7ec6109e7ebccb2d2b7c4fb fixed the vulnerable transitive dependency so need to explicitly manage it anymore.
----
📚 Documentation preview 📚: https://bowtie-json-schema--1289.org.readthedocs.build/en/1289/

no need to explicitly manage "braces" package

---

implementations/cpp-jsontoolkit/bowtie_jsontoolkit.cpp

Other C++ implementations use "C++" while I set "Cpp"
----
📚 Documentation preview 📚: https://bowtie-json-schema--1297.org.readthedocs.build/en/1297/

Correctly set the language for JSON Toolkit

---

.github/workflows/ci.yml

Unfortunately, creating a concurrency group that will work only for PR is impossible. It will also affect the pushes to branches and scheduled workflows. If only PRs should be affected, probably, the best option would be to create a reusable workflow from CI workflow and create two separate workflows that use it: one for PRs (with concurrency group) and one for pushes to branches/tags and scheduled runs.
Using `${{ github.event_name }}` should prevent collisions between scheduled executions and pushes to the main branch.
Resolves #1202
----
📚 Documentation preview 📚: https://bowtie-json-schema--1301.org.readthedocs.build/en/1301/

Add concurrency group for ci workflow

---

.github/workflows/images.yml

@Julian just this minor fix I noticed while skimming through this file to get an idea of how to write a similar one for building multiple images.
----
📚 Documentation preview 📚: https://bowtie-json-schema--1306.org.readthedocs.build/en/1306/

Remove custom python code for listing implementations and instead use `bowtie filter-implementations` 

---

bowtie/_containers.py

@Julian is this fine ? It works now. Though I still have to write "image:" prefix for it to work.

Container runtime pulls version tagged image if available or the latest one as default.

---

.github/workflows/versioned-report.yml

@Julian sorry for closing the other PR since it had a lot of unnecessary commits but this one's clean now. [Here's](https://github.com/adwait-godbole/bowtie/actions/runs/9674687356) the workflow run on my fork. Let me know what you think about this now and also the below thought.
What I am planning to do now is to modify our current `report.yml` workflow to download the artifacts that were published by this `versioned-report.yml` workflow's last run and every time upload it alongside other implementation reports which are generated by `report.yml` itself. This way we will have the traditionally generated reports for the latest versions of all implementations by `report.yml` and also alongside them we will have these versioned reports which were generated by `versioned-report.yml`. With …

A new `versioned-report.yml` workflow for generating reports for different versions of an implementation

---

.github/workflows/ui.yml

@Julian this would include the versioned reports in the frontend / github-pages site artifact.
----
📚 Documentation preview 📚: https://bowtie-json-schema--1377.org.readthedocs.build/en/1377/

Include latest versioned reports in UI deployment artifact

---

frontend/package.json
frontend/pnpm-lock.yaml
frontend/src/components/Cases/CaseResultSvg.test.tsx

@Julian as per over [here](https://github.com/facebook/react/blob/main/packages/react-test-renderer/README.md) and also over [here](https://react.dev/warnings/react-test-renderer), `react-test-renderer` seems to have been deprecated so ig its better to use `@testing-library/react` as recommended over there.
Thanks.
----
📚 Documentation preview 📚: https://bowtie-json-schema--1430.org.readthedocs.build/en/1430/

Remove deprecated `react-test-renderer`

---

bowtie/_cli.py
bowtie/tests/test_integration.py

Fixes #1414 
----
📚 Documentation preview 📚: https://bowtie-json-schema--1431.org.readthedocs.build/en/1431/

`bowtie summary --show failures` should return nonzero status on failures

---

bowtie/_benchmarks.py
bowtie/_cli.py

----
📚 Documentation preview 📚: https://bowtie-json-schema--1444.org.readthedocs.build/en/1444/

By default, filter-benchmarks should return all benchmarks instead of just default ones

---

.github/workflows/report.yml

----
📚 Documentation preview 📚: https://bowtie-json-schema--1460.org.readthedocs.build/en/1460/

Update `report.yml` to take advantage of `bowtie summary` exiting with nonzero status

---

.github/workflows/benchmark.yml
.github/workflows/report.yml

----
📚 Documentation preview 📚: https://bowtie-json-schema--1458.org.readthedocs.build/en/1458/

Add Benchmarks workflow

---

.github/workflows/benchmark.yml

I had tested the workflow using, since the latest benchmark changes were not there in the latest release:
This works fine
```
- name: Set up Python
uses: actions/setup-python@v4
with:
python-version: '3.12'
- name: Install Bowtie
run: |
pip install -e .
```
However now using, 
This doesnt work
```
- name: Install Bowtie
uses: ./
```
Since the latest release has been done, the workflow is failing on the python script step saying `url` library not found. I dont understand why though @Julian . Both code should work the same functionality wise right ?
ERROR:
```
Run python - <<EOF
python - <<EOF
from pathlib import Path
from bowtie._benchmarks import combine_benchmark_reports_to_serialized as combine
Path("draft[2](https://github.com/sudo-jarvis/bowtie/actions/runs/10547927252/job/29221319098# …
```

Bug Fix: Somehow the former gives error in terms of some url library missing during the workflow

---

bowtie/schemas/cli/summary.json
bowtie/schemas/models/unsuccessfulTests.json
bowtie/tests/fauxmplementations/lintsonschema/schemas/cli/summary.json
bowtie/tests/fauxmplementations/lintsonschema/schemas/models/unsuccessfulTests.json

----
📚 Documentation preview 📚: https://bowtie-json-schema--1485.org.readthedocs.build/en/1485/

reusable `unsuccessfulTests` schema from `summary.json`

---

bowtie/__init__.py
bowtie/_cli.py
bowtie/_core.py
bowtie/_report.py
bowtie/_suite.py

@Julian I tried getting this to work.
----
📚 Documentation preview 📚: https://bowtie-json-schema--1487.org.readthedocs.build/en/1487/

Add `--versions` option to `bowtie info` for fetching versions from ghcr registry

---

implementations/rust-jsonschema/Cargo.toml

As of `0.19` these features are deprecated and related functionality is enabled by default.
Btw, I see that [the report](https://bowtie.report/#/implementations/rust-jsonschema) still shows data for `0.18.1`, even though there were some updates for `rust-jsonschema` merged here:
Is there something I am missing? recently there were a few fixes, so I was wondering when the badges will reflect them :)
----
📚 Documentation preview 📚: https://bowtie-json-schema--1527.org.readthedocs.build/en/1527/

Remove deprecated `rust-jsonschema` features

---

implementations/cpp-blaze/Dockerfile

See: https://github.com/bowtie-json-schema/bowtie/pull/1593#issuecomment-2418082033
----
📚 Documentation preview 📚: https://bowtie-json-schema--1607.org.readthedocs.build/en/1607/

Fix the Blaze run image to have `libstdc++`

---

implementations/js-hyperjump/bowtie_hyperjump.js
implementations/js-hyperjump/package.json

String comparison is not sufficient for version checks. The current code broke when I added v1.10.0.
----
📚 Documentation preview 📚: https://bowtie-json-schema--1747.org.readthedocs.build/en/1747/

Fix bug in hyperjump harness

---

frontend/src/components/NotFound.test.tsx
frontend/src/components/NotFound.tsx
frontend/src/index.tsx

Closes: #1752 
----
📚 Documentation preview 📚: https://bowtie-json-schema--1753.org.readthedocs.build/en/1753/

Added Custom 404 Page.

---

implementations/cpp-jsoncons/bowtie_jsoncons.cpp

This PR sets the default dialect in bowtie_jsoncons.cpp
----
📚 Documentation preview 📚: https://bowtie-json-schema--1821.org.readthedocs.build/en/1821/

[cpp-jsoncons] Set default dialect option

---

implementations/rust-jsonschema/src/main.rs

The version of `jsonschema` was updated in #1828. However, the new version contains a few breaking changes that cause the image build to fail. This PR makes changes according to the change log in the library
----
📚 Documentation preview 📚: https://bowtie-json-schema--1830.org.readthedocs.build/en/1830/

fix: Update implementation according to the latest breaking changes

---

bowtie/tests/test_benchmarks.py
bowtie/tests/test_integration.py
bowtie/tests/test_report.py

Fixes pytest warning:
```
=============================== warnings summary ===============================
bowtie/_core.py:721
/home/runner/work/bowtie/bowtie/bowtie/_core.py:721: PytestCollectionWarning: cannot collect test class 'TestCase' because it has a __init__ constructor (from: bowtie/tests/test_benchmarks.py)
@frozen
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```
----
📚 Documentation preview 📚: https://bowtie-json-schema--1868.org.readthedocs.build/en/1868/

chore: fix pytest warnings

---

.github/workflows/images.yml
implementations/go-gojsonschema/Dockerfile
implementations/go-jsonschema/Dockerfile

This PR updated Dockerfiles for golang harnesses to support cross-platform compilation. QEMU is not required in this case and can be disabled
----
📚 Documentation preview 📚: https://bowtie-json-schema--1885.org.readthedocs.build/en/1885/

Enable cross-platform compilation for golang implementations

---

bowtie/_cli.py
bowtie/_core.py
bowtie/benchmarks/keywords/additionalProperties.py

PR fixes newly reported alerts:
- [TC006](https://docs.astral.sh/ruff/rules/runtime-cast-value/) [*] Add quotes to type expression in `typing.cast()`
- [C420](https://docs.astral.sh/ruff/rules/unnecessary-dict-comprehension-for-iterable/) [*] Unnecessary dict comprehension for iterable; use `dict.fromkeys`
----
📚 Documentation preview 📚: https://bowtie-json-schema--1890.org.readthedocs.build/en/1890/

Fix TC006 and C420 ruff alerts

---

frontend/package.json
frontend/pnpm-lock.yaml

This PR resolves vulnerabilities found by `ui(audit)`.
It also forces resolution for `prismjs` - a vulnerability in versions `< 1.30.0`. One of the dependencies transitively depends on an older version of the library and it does not look like it will be updated soon...
Path: `. > react-syntax-highlighter@15.6.1 > refractor@3.6.0  > prismjs@1.27.0`
PR for update: https://github.com/react-syntax-highlighter/react-syntax-highlighter/pull/590
----
📚 Documentation preview 📚: https://bowtie-json-schema--1891.org.readthedocs.build/en/1891/

Update dependencies in UI to fix audit job

---

.github/workflows/ci.yml
.github/workflows/images.yml
hatch_build.py
pyproject.toml

A part of POC #1849 is a modification of how bowtie collects the information about known implementation.
This PR adds functionality to collect known implementations using [GitHub Packages API](https://docs.github.com/en/rest/packages/packages?apiVersion=2022-11-28#list-packages-for-an-organization).
I am not a Python developer - sorry in advance if I made some stupid mistakes)
----
📚 Documentation preview 📚: https://bowtie-json-schema--1867.org.readthedocs.build/en/1867/

Use GitHub packages API to collect known implementations

---

implementations/php-justinrainbow-json-schema/composer.json
implementations/php-justinrainbow-json-schema/composer.lock

New versions of our library don't seem to trigger a rebuild of bowtie report. I'm suspecting this is due to the lack of the `composer.lock` file. Therefore this PR adds the `composer.lock` file to try and fix the dependabot action end start the whole process of trying to update the report of the `php-justinrainbow-json-schema` implementation. 
----
📚 Documentation preview 📚: https://bowtie-json-schema--1913.org.readthedocs.build/en/1913/

build: include composer.lock file to enable dependabot

---

implementations/php-justinrainbow-json-schema/Dockerfile

Due to missing composer files the container reported `dev-master` in the start command reply instead of the installed version.
----
📚 Documentation preview 📚: https://bowtie-json-schema--1917.org.readthedocs.build/en/1917/

Fix version displayed for PHP JustinRainbow Json-Schema

---

bowtie/_cli.py

I was testing with the summary output in Markdown and notice an issue with the header for each schema. As it was without a newline and directly added to the end of the earlier output, which in this case was a table. While fixing this I also noticed the schema was without a code fence so I've added them as well.
<details><summary>Misformatted Markdown</summary>
<p>
See the final line where the header is added directly after the table.
```
{
"items": [
{}
],
"additionalItems": {
"type": "integer"
}
}
| Instance | justinrainbow-json-schema (php) |
|:-------------------:|:-------:|
|      |  valid  |
|  | invalid |### 2. Schema:
```
</p>
</details> 
This is my first time contributing to Python code. So could be it requires some tweaks, in which case just let me know.
----
📚 Documentation …

fix: fixes a missing new line before the h3 and wrap schema in a codefence in bowtie summary command

---

.github/workflows/versioned-report.yml

PR adds a schedule trigger to the [versioned-report.yml](https://github.com/bowtie-json-schema/bowtie/blob/main/.github/workflows/versioned-report.yml) workflow (as suggested in #1915).
The automatic build is scheduled for Sunday at 23:30 (45 minutes before the report workflow is scheduled) to provide the fresh artifacts with versioned reports (the latest versioned report runs took about 40 minutes, so I have added 5 more minutes just in case).
I don't think there is a point in triggering the workflow more often than once a week - we don't have many test harnesses with different versions' support
----
📚 Documentation preview 📚: https://bowtie-json-schema--1920.org.readthedocs.build/en/1920/

Add schedule trigger for versioned report workflow

---

implementations/php-justinrainbow-json-schema/composer.json
implementations/php-justinrainbow-json-schema/composer.lock

As mentioned by @OptimumCode in #1917 for some reason I've added an incorrect lock file. This PR corrects that issue.
----
📚 Documentation preview 📚: https://bowtie-json-schema--1921.org.readthedocs.build/en/1921/

fix: correct version in lock file; bump minimum minor version

---

.github/workflows/report.yml

The PR adds a GITHUB_TOKEN into env variables during test suite execution. There is a chance that without a token we hit a rate limit. Example here:
https://github.com/bowtie-json-schema/bowtie/actions/runs/14143123995/job/39627152056
PR also reduces the scope of write permissions only to the job responsible for site deployment
----
📚 Documentation preview 📚: https://bowtie-json-schema--1922.org.readthedocs.build/en/1922/

Provide GITHUB_TOKEN during test suite execution

---

bowtie/_benchmarks.py
bowtie/_commands.py
bowtie/_containers.py
bowtie/_report.py

The new version of `pyright` checks that the function return type matches the defined type. For that we need to specify type parameters in the factory function.
We didn't ignore the error because this new check is added to existing one and ignoring the new error would mean we completely disable the type checking for those fields
----
📚 Documentation preview 📚: https://bowtie-json-schema--1950.org.readthedocs.build/en/1950/

Explicit type parameters in factory function

---

implementations/elixir-jsv/mix.exs

The [latest report is still using JSV 0.5.1](https://bowtie.report/#/?language=elixir) whereas a `0.7.1` exists.
So let's try to force the update.
But I am not sure why it is the case. The orginal code uses `~> 0.3` which sucessfully pulled the `0.5.1`, so it should pull `0.7.x` as well.
It's probably because of the Docker cache. JSV 0.5.1 was released on Mar 28, 2025 ; do you remember clearing the cache around that time?
What could we do to bust the docker cache every month or so? Could you for instance pass a build arg with `2025-05` that we can use in a Dockerfile so it's busted automatically?
----
📚 Documentation preview 📚: https://bowtie-json-schema--2005.org.readthedocs.build/en/2005/

chore(deps): bump jsv library in elixir-jsv implementation

---

.github/workflows/versioned-report.yml

PR fixes the problem caused by #1916 during report verification. Instead of the version, the step used the `latest` tag and tried to check if the report for that tag existed (but when generating the report, we replaced the `latest` tag with the actual version).
Now, instead of replacing the `latest` tag during report generation, we replace it before dumping the versions into the matix-versions.json file
----
📚 Documentation preview 📚: https://bowtie-json-schema--2020.org.readthedocs.build/en/2020/

dump the exact version for the latest tag instead of tag itself
